### ISSUE TITLE
syntax highlight problem with long lines

### ISSUE THREAD

**Issue by tk3369** [atom/language-xml#32] opened 2015-07-15 20:54 UTC
For example,

```xml
<hello world1="123" world2="123" world3="123" world4="123" world5="123" world6="123" world7="123" world8="123" world9="123" world10="123" world11="123" world12="123" world13="123" world14="123" world15="123" world16="123" world17="123" world18="123" world19="123" world20="123"/>
```
stops highlighting world17's string attribute.

**Comment by 50Wliu** [comment] 2015-07-15 22:01
Hi @tk3369, this is a duplicate of atom/atom#1667 - please subscribe there for updates instead.

**Closed by 50Wliu** 2015-07-15 22:01 UTC
