### ISSUE TITLE
Code folding fails with multiline CDATA text

### ISSUE THREAD

**Issue by alexchandel** [atom/language-xml#77] opened 2017-03-22 23:55 UTC
Code folding on matched tags fails when multiline CDATA text is present in any tag that's not the topmost one. For example, the `Inner` tag in this fails to fold:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Outer>
    <Inner>
        <![CDATA[LINE 1
LINE 2]]>
    </Inner>
</Outer>
```

**Comment by 50Wliu** [comment] 2017-03-23 01:51
Thanks for taking the time to contribute!

We noticed that this is a duplicate of atom/atom#3442 and atom/atom#11838. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-03-23 01:51 UTC
