### ISSUE TITLE
Text underlining is wrong when using shorthanded tag closures

### ISSUE THREAD

**Issue by Nokel81** [atom/language-xml#83] opened 2017-06-20 13:39 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The "highlight other tag" feature where the tag in xml or html is underlined when the cursor is within the tag name is wrong when some of the tags have the shorthand for tag ends

### Steps to Reproduce

![highlighting](https://user-images.githubusercontent.com/8225332/27335903-00487c7e-559c-11e7-8612-332327842272.PNG)

**Expected behavior:** The first and the last `xs:element` tags are underlined

**Actual behavior:** The last `xs:element` and the closest back up the file are underlined

**Reproduces how often:** Whenever there are preceding tags of the same name with the `/>` ending shorthand

### Versions

Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python
git 2.10.2.win
visual studio

**Comment by 50Wliu** [comment] 2017-06-20 16:37
Thanks for taking the time to contribute!

We noticed that this is a duplicate of atom/bracket-matcher#203. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-06-20 16:37 UTC
